name: Render with SimplyMarkdown

on:
  push:
    branches: 
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SimplyMarkdown
        run: |
          git clone https://github.com/cemreefe/SimplyMarkdown.git /tmp/SimplyMarkdown
          pip install /tmp/SimplyMarkdown

      - name: Build site
        run: |
          simplymarkdown build \
            -i source \
            -o output \
            --title "Example Blog" \
            --favicon 🟢 \
            --root 'https://mypage.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
