"""Table of Contents module extension for SimplyMarkdown."""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from typing import Any

from markdown.blockprocessors import BlockProcessor
from markdown.extensions import Extension


class TocModuleExtension(Extension):
    """Markdown extension to generate a table of contents module.

    Usage in markdown:
        ! toc              - Generate TOC from headers
        ! toc:maxlevel:3   - Generate TOC up to h3
    """

    def __init__(self, **kwargs: Any):
        super().__init__(**kwargs)
        self.config = {"max_level": [6, "Maximum header level to include in TOC"]}

    def extendMarkdown(self, md: Any) -> None:
        """Register the TOC module block processor."""
        toc_processor = TocModuleBlockProcessor(self.getConfigs(), md.parser)
        toc_processor.md = md
        md.parser.blockprocessors.register(toc_processor, "toc_module", 174)


class TocModuleBlockProcessor(BlockProcessor):
    """Block processor for generating table of contents."""

    PATTERN = re.compile(r"^!\s*toc(?::maxlevel:(\d+))?$", re.IGNORECASE)

    def __init__(self, config: dict[str, Any], parser: Any):
        super().__init__(parser)
        self.max_level = int(config["max_level"])

    def test(self, parent: ET.Element, block: str) -> bool:  # noqa: ARG002
        """Test if the block matches the TOC module pattern."""
        return bool(self.PATTERN.match(block.strip()))

    def run(self, parent: ET.Element, blocks: list[str]) -> None:
        """Process the TOC module block."""
        block = blocks.pop(0)
        match = self.PATTERN.match(block.strip())
        if not match:
            return

        # Get max level from pattern if specified
        if match.group(1):
            self.max_level = int(match.group(1))

        # Create TOC placeholder that will be filled after markdown is processed
        toc_div = ET.Element("div", attrib={"class": "toc-module"})

        # The actual TOC will be generated by the markdown.extensions.toc extension
        # This placeholder tells the template to include [TOC]
        toc_placeholder = ET.Element("div", attrib={"class": "toc-placeholder"})
        toc_placeholder.text = "[TOC]"
        toc_div.append(toc_placeholder)

        parent.append(toc_div)
